spring:
  datasource:
    url: jdbc:mysql://localhost:3306/comic_king?useUnicode=true&zeroDateTimeBehavior=convertToNull&characterEncoding=utf-8&useSSL=false
    username: ENC[HbIXjEgLOIOBbxL3/1rJ1A==]
    password: ENC[LoEC2/eJElnyqN0b9ZyJUw==]

jasypt:
  encryptor:
    # 任意的随机字符串均可
    password: G0CvDz7oJn6
    property:
      # 自定义属性规则，默认前缀是“ENC(”，后缀为“)”
      prefix: "ENC["
      suffix: "]"


